apiVersion: v2
appVersion: 2024.1.3
description: A Helm chart for Home Assistant
maintainers:
- email: sklenar.pav@gmail.com
  name: pajikos
name: home-assistant
type: application
version: 0.2.25
kubeVersion: ">=1.16.0-0"
keywords:
  - home-assistant
  - hass
  - homeassistant
home: https://github.com/pajikos/home-assistant-helm-chart
icon: https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Home_Assistant_Logo.svg/519px-Home_Assistant_Logo.svg.png
sources:
  - https://github.com/pajikos/home-assistant-helm-chart
  - https://github.com/cdr/code-server
  - https://github.com/pajikos/home-assistant-helm-chart/tree/main/charts/home-assistant
